exports.College = require('./components/college.vue')
exports.Department = require('./components/department.vue')
exports.Degree = require('./components/degree.vue')
exports.Grade = require('./components/grade.vue')
exports.Trans = require('./components/trans.vue')
